spring:
  application:
    name: ${APPLICATION_NAME:api-gateway}
  cloud:
    gateway:
      enabled: true
  devtools:
    livereload:
      enabled: false

server:
  port: ${SERVER_PORT:8080}

services:
  uri:
    user-service: http://localhost:8081
    company-service: http://localhost:8082

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.request]": true
#logging:
#  level:
#    org.springframework.cloud.gateway: trace
