spring:
  application:
    name: ${APPLICATION_NAME:api-gateway}
  cloud:
    gateway:
      enabled: true
  devtools:
    livereload:
      enabled: false

server:
  port: 8080

services:
  uri:
    user-service: http://localhost:8081
    company-service: http://localhost:8082

#logging:
#  level:
#    org.springframework.cloud.gateway: trace
