spring:
  application:
    name: ${APPLICATION_NAME:user-service}
  devtools:
    livereload:
      enabled: false

server:
  port: ${SERVER_PORT:8081}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.request]": true